use super::types::{Aide, AideId, Categorie};
use crate::engine::rules;

pub fn all_aides() -> Vec<Aide> {
    vec![
        // ── Revenus minimaux ──────────────────────────────────────────────────
        Aide {
            id: AideId::Rsa,
            slug: "rsa",
            nom: "RSA — Revenu de Solidarite Active",
            description: "Revenu minimum pour les personnes sans emploi ou avec faibles ressources.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(0.0),
            montant_max: Some(646.52),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/N19775",
            calculer: rules::calc_rsa,
        },
        Aide {
            id: AideId::PrimeActivite,
            slug: "prime-activite",
            nom: "Prime d'Activite",
            description: "Complement de revenus pour les travailleurs aux faibles salaires. Accessible des 18 ans.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(0.0),
            montant_max: Some(633.21),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F2882",
            calculer: rules::calc_prime_activite,
        },
        Aide {
            id: AideId::Ass,
            slug: "ass",
            nom: "ASS — Allocation de Solidarite Specifique",
            description: "Allocation pour les personnes en fin de droits ARE ayant travaille au moins 5 ans.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(0.0),
            montant_max: Some(579.90),
            periodicite: "mensuel",
            organisme: "France Travail",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12484",
            calculer: rules::calc_ass,
        },
        Aide {
            id: AideId::AllocationChomage,
            slug: "are",
            nom: "ARE — Allocation de Retour a l'Emploi",
            description: "Indemnisation chomage versee par France Travail apres une perte d'emploi involontaire.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(0.0),
            montant_max: Some(1800.0),
            periodicite: "mensuel",
            organisme: "France Travail",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F14860",
            calculer: rules::calc_allocation_chomage,
        },
        // ── Logement ─────────────────────────────────────────────────────────
        Aide {
            id: AideId::Apl,
            slug: "apl",
            nom: "APL — Aide Personnalisee au Logement",
            description: "Aide au paiement du loyer pour les locataires. Montant selon revenus, loyer et zone.",
            categorie: Categorie::Logement,
            montant_min: Some(0.0),
            montant_max: Some(380.0),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12006",
            calculer: rules::calc_apl,
        },
        Aide {
            id: AideId::Als,
            slug: "als",
            nom: "ALS — Allocation de Logement Sociale",
            description: "Aide logement pour ceux ne beneficiant pas de l'APL (personne seule, etudiant, retraite).",
            categorie: Categorie::Logement,
            montant_min: Some(0.0),
            montant_max: Some(300.0),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F1215",
            calculer: rules::calc_als,
        },
        Aide {
            id: AideId::Visale,
            slug: "visale",
            nom: "Visale — Garantie Caution Locative",
            description: "Garantie gratuite de loyer impayee pour les locataires < 30 ans ou en debut d'emploi.",
            categorie: Categorie::Logement,
            montant_min: None,
            montant_max: None,
            periodicite: "unique",
            organisme: "Action Logement",
            url_info: "https://www.visale.fr",
            calculer: rules::calc_visale,
        },
        Aide {
            id: AideId::MaPrimeRenov,
            slug: "ma-prime-renov",
            nom: "MaPrimeRenov'",
            description: "Subvention pour travaux de renovation energetique. Montant selon revenus et travaux.",
            categorie: Categorie::Logement,
            montant_min: Some(150.0),
            montant_max: Some(500.0),
            periodicite: "mensuel",
            organisme: "ANAH",
            url_info: "https://www.maprimerenov.gouv.fr",
            calculer: rules::calc_ma_prime_renov,
        },
        // ── Sante / Handicap ─────────────────────────────────────────────────
        Aide {
            id: AideId::Aah,
            slug: "aah",
            nom: "AAH — Allocation aux Adultes Handicapes",
            description: "Revenu garanti pour les personnes handicapees. Deconjugalisee depuis octobre 2023.",
            categorie: Categorie::Sante,
            montant_min: Some(0.0),
            montant_max: Some(1033.32),
            periodicite: "mensuel",
            organisme: "CAF",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12242",
            calculer: rules::calc_aah,
        },
        Aide {
            id: AideId::Mva,
            slug: "mva",
            nom: "MVA — Majoration Vie Autonome",
            description: "Complement de l'AAH pour les personnes handicapees vivant seules en logement autonome.",
            categorie: Categorie::Sante,
            montant_min: Some(107.48),
            montant_max: Some(107.48),
            periodicite: "mensuel",
            organisme: "CAF",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12242",
            calculer: rules::calc_mva,
        },
        Aide {
            id: AideId::Pch,
            slug: "pch",
            nom: "PCH — Prestation de Compensation du Handicap",
            description: "Aide pour les frais lies au handicap : aide humaine, aides techniques, amenagement.",
            categorie: Categorie::Sante,
            montant_min: Some(0.0),
            montant_max: Some(1743.0),
            periodicite: "mensuel",
            organisme: "Departement / MDPH",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F14202",
            calculer: rules::calc_pch,
        },
        Aide {
            id: AideId::Aeeh,
            slug: "aeeh",
            nom: "AEEH — Allocation Education Enfant Handicape",
            description: "Aide pour les familles ayant un enfant handicape de moins de 20 ans.",
            categorie: Categorie::Sante,
            montant_min: Some(140.33),
            montant_max: Some(1100.0),
            periodicite: "mensuel",
            organisme: "CAF / MDPH",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F14809",
            calculer: rules::calc_aeeh,
        },
        Aide {
            id: AideId::Asi,
            slug: "asi",
            nom: "ASI — Allocation Supplementaire d'Invalidite",
            description: "Complement de ressources pour les invalides < 65 ans avec une faible pension.",
            categorie: Categorie::Sante,
            montant_min: Some(0.0),
            montant_max: Some(466.26),
            periodicite: "mensuel",
            organisme: "CPAM / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F16385",
            calculer: rules::calc_asi,
        },
        Aide {
            id: AideId::PensionInvalidite,
            slug: "pension-invalidite",
            nom: "Pension d'Invalidite",
            description: "Revenu de remplacement pour les assures dont la capacite de travail est reduite de 2/3.",
            categorie: Categorie::Sante,
            montant_min: Some(0.0),
            montant_max: Some(1500.0),
            periodicite: "mensuel",
            organisme: "CPAM",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F672",
            calculer: rules::calc_pension_invalidite,
        },
        Aide {
            id: AideId::Css,
            slug: "css",
            nom: "CSS — Complement Sante Solidaire",
            description: "Complementaire sante gratuite ou a 1€/jour pour les foyers modestes.",
            categorie: Categorie::Sante,
            montant_min: None,
            montant_max: Some(1100.0),
            periodicite: "annuel",
            organisme: "CPAM",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F10027",
            calculer: rules::calc_css,
        },
        // ── Famille ──────────────────────────────────────────────────────────
        Aide {
            id: AideId::AllocationsFamiliales,
            slug: "allocations-familiales",
            nom: "Allocations Familiales",
            description: "Versement mensuel pour les foyers avec 2 enfants ou plus de moins de 20 ans.",
            categorie: Categorie::Famille,
            montant_min: Some(37.77),
            montant_max: Some(500.0),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F13213",
            calculer: rules::calc_allocations_familiales,
        },
        Aide {
            id: AideId::ComplementFamilial,
            slug: "complement-familial",
            nom: "Complement Familial",
            description: "Aide pour les familles avec 3 enfants ou plus, tous ages de 3 a 21 ans.",
            categorie: Categorie::Famille,
            montant_min: Some(173.08),
            montant_max: Some(259.09),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F13214",
            calculer: rules::calc_complement_familial,
        },
        Aide {
            id: AideId::Paje,
            slug: "paje",
            nom: "PAJE — Prestation d'Accueil du Jeune Enfant",
            description: "Allocation de base pour les enfants de moins de 3 ans selon revenus du foyer.",
            categorie: Categorie::Famille,
            montant_min: Some(98.30),
            montant_max: Some(196.59),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F2552",
            calculer: rules::calc_paje,
        },
        Aide {
            id: AideId::Asf,
            slug: "asf",
            nom: "ASF — Allocation de Soutien Familial",
            description: "Aide pour les parents seuls dont l'enfant ne recoit pas de pension alimentaire.",
            categorie: Categorie::Famille,
            montant_min: Some(170.62),
            montant_max: Some(500.0),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F815",
            calculer: rules::calc_asf,
        },
        Aide {
            id: AideId::AllocationRentreeScolaire,
            slug: "ars",
            nom: "ARS — Allocation de Rentree Scolaire",
            description: "Aide annuelle versee en aout pour les enfants scolarises de 6 a 18 ans.",
            categorie: Categorie::Famille,
            montant_min: Some(423.48),
            montant_max: Some(462.32),
            periodicite: "annuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F1878",
            calculer: rules::calc_allocation_rentree_scolaire,
        },
        // ── Energie ──────────────────────────────────────────────────────────
        Aide {
            id: AideId::ChequeEnergie,
            slug: "cheque-energie",
            nom: "Cheque Energie",
            description: "Aide annuelle automatique sur facture energie ou logement social. Envoyee en avril.",
            categorie: Categorie::Energie,
            montant_min: Some(48.0),
            montant_max: Some(277.0),
            periodicite: "annuel",
            organisme: "DGFiP / ADEME",
            url_info: "https://chequeenergie.gouv.fr",
            calculer: rules::calc_cheque_energie,
        },
        // ── Retraite ─────────────────────────────────────────────────────────
        Aide {
            id: AideId::Aspa,
            slug: "aspa",
            nom: "ASPA — Minimum Vieillesse",
            description: "Revenu minimum garanti pour les retraites modestes. Recuperation sur succession > 105300€.",
            categorie: Categorie::Retraite,
            montant_min: Some(0.0),
            montant_max: Some(1043.59),
            periodicite: "mensuel",
            organisme: "Caisse de retraite / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F16871",
            calculer: rules::calc_aspa,
        },
        Aide {
            id: AideId::MinimumRetraite,
            slug: "minimum-retraite",
            nom: "MICO — Minimum Contributif Retraite",
            description: "Complement de retraite pour porter la pension au minimum contributif (934€/mois).",
            categorie: Categorie::Retraite,
            montant_min: Some(0.0),
            montant_max: Some(934.27),
            periodicite: "mensuel",
            organisme: "CNAV / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12004",
            calculer: rules::calc_minimum_retraite,
        },
        // ── Jeunes ───────────────────────────────────────────────────────────
        Aide {
            id: AideId::Cej,
            slug: "cej",
            nom: "CEJ — Contrat Engagement Jeune",
            description: "Accompagnement intensif + allocation jusqu'a 528€/mois pour les 16-25 ans.",
            categorie: Categorie::Jeunes,
            montant_min: Some(0.0),
            montant_max: Some(528.60),
            periodicite: "mensuel",
            organisme: "France Travail / Mission Locale",
            url_info: "https://www.1jeune1solution.gouv.fr/contrat-engagement-jeune",
            calculer: rules::calc_cej,
        },
        Aide {
            id: AideId::BourceCrous,
            slug: "bourse-crous",
            nom: "Bourse CROUS sur Criteres Sociaux",
            description: "Bourse etudiante de 106 a 563€/mois selon revenus familiaux. 7 echelons.",
            categorie: Categorie::Jeunes,
            montant_min: Some(106.65),
            montant_max: Some(563.50),
            periodicite: "mensuel",
            organisme: "CROUS",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12214",
            calculer: rules::calc_bourse_crous,
        },
        Aide {
            id: AideId::PassCulture,
            slug: "pass-culture",
            nom: "Pass Culture",
            description: "Credit de 300€ utilisable sur l'application passculture.app a l'age de 18 ans.",
            categorie: Categorie::Jeunes,
            montant_min: Some(300.0),
            montant_max: Some(300.0),
            periodicite: "unique",
            organisme: "Ministere de la Culture",
            url_info: "https://passculture.app",
            calculer: rules::calc_pass_culture,
        },
        // ── Divers ───────────────────────────────────────────────────────────
        Aide {
            id: AideId::PrimeNoel,
            slug: "prime-noel",
            nom: "Prime de Noel RSA",
            description: "Versement exceptionnel en decembre pour les beneficiaires du RSA ou ASS.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(152.45),
            montant_max: Some(500.0),
            periodicite: "annuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F1325",
            calculer: rules::calc_prime_noel,
        },
        Aide {
            id: AideId::AideJuridictionnelle,
            slug: "aide-juridictionnelle",
            nom: "Aide Juridictionnelle",
            description: "Prise en charge totale ou partielle des frais de justice selon les revenus.",
            categorie: Categorie::RevenusEmploi,
            montant_min: None,
            montant_max: None,
            periodicite: "unique",
            organisme: "Ministere de la Justice",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F18074",
            calculer: rules::calc_aide_juridictionnelle,
        },
    ]
}
