use super::types::{Aide, AideId, Categorie};
use crate::engine::rules;

pub fn all_aides() -> Vec<Aide> {
    vec![
        Aide {
            id: AideId::Rsa,
            slug: "rsa",
            nom: "RSA — Revenu de Solidarite Active",
            description: "Revenu minimum pour les personnes sans emploi ou avec faibles ressources. Verse par la CAF ou MSA.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(0.0),
            montant_max: Some(635.71),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/N19775",
            calculer: rules::calc_rsa,
        },
        Aide {
            id: AideId::Apl,
            slug: "apl",
            nom: "APL — Aide Personnalisee au Logement",
            description: "Aide au paiement du loyer pour les locataires. Montant calcule selon revenus, loyer et zone geographique.",
            categorie: Categorie::Logement,
            montant_min: Some(0.0),
            montant_max: Some(380.0),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12006",
            calculer: rules::calc_apl,
        },
        Aide {
            id: AideId::PrimeActivite,
            slug: "prime-activite",
            nom: "Prime d'Activite",
            description: "Complement de revenus pour les travailleurs aux faibles salaires. Accessible des 18 ans.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(0.0),
            montant_max: Some(635.71),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F2882",
            calculer: rules::calc_prime_activite,
        },
        Aide {
            id: AideId::Aah,
            slug: "aah",
            nom: "AAH — Allocation aux Adultes Handicapes",
            description: "Aide pour les personnes en situation de handicap (RQTH ou invalidite reconnue). Verse par la CAF.",
            categorie: Categorie::Sante,
            montant_min: Some(0.0),
            montant_max: Some(1016.85),
            periodicite: "mensuel",
            organisme: "CAF",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F12242",
            calculer: rules::calc_aah,
        },
        Aide {
            id: AideId::ChequeEnergie,
            slug: "cheque-energie",
            nom: "Cheque Energie",
            description: "Aide annuelle pour payer les factures d'energie. Attribution automatique via la DGFiP.",
            categorie: Categorie::Energie,
            montant_min: Some(48.0),
            montant_max: Some(277.0),
            periodicite: "annuel",
            organisme: "DGFiP / ADEME",
            url_info: "https://chequeenergie.gouv.fr",
            calculer: rules::calc_cheque_energie,
        },
        Aide {
            id: AideId::AllocationsFamiliales,
            slug: "allocations-familiales",
            nom: "Allocations Familiales",
            description: "Versement mensuel pour les foyers avec 2 enfants ou plus a charge de moins de 20 ans.",
            categorie: Categorie::Famille,
            montant_min: Some(140.27),
            montant_max: Some(500.0),
            periodicite: "mensuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F13213",
            calculer: rules::calc_allocations_familiales,
        },
        Aide {
            id: AideId::Css,
            slug: "css",
            nom: "CSS — Complement Sante Solidaire",
            description: "Prise en charge complementaire sante gratuite pour les foyers a faibles revenus. Remplace la CMU-C.",
            categorie: Categorie::Sante,
            montant_min: None,
            montant_max: Some(1200.0),
            periodicite: "annuel",
            organisme: "CPAM",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F10027",
            calculer: rules::calc_css,
        },
        Aide {
            id: AideId::Cej,
            slug: "cej",
            nom: "CEJ — Contrat Engagement Jeune",
            description: "Accompagnement intensif vers l'emploi pour les 16-25 ans avec allocation mensuelle.",
            categorie: Categorie::Jeunes,
            montant_min: Some(0.0),
            montant_max: Some(528.60),
            periodicite: "mensuel",
            organisme: "France Travail / Mission Locale",
            url_info: "https://www.1jeune1solution.gouv.fr/contrat-engagement-jeune",
            calculer: rules::calc_cej,
        },
        Aide {
            id: AideId::Aspa,
            slug: "aspa",
            nom: "ASPA — Allocation de Solidarite aux Personnes Agees",
            description: "Revenu minimum pour les retraites aux faibles ressources. Anciennement minimum vieillesse.",
            categorie: Categorie::Retraite,
            montant_min: Some(0.0),
            montant_max: Some(961.08),
            periodicite: "mensuel",
            organisme: "Caisse de retraite / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F16871",
            calculer: rules::calc_aspa,
        },
        Aide {
            id: AideId::PrimeNoel,
            slug: "prime-noel",
            nom: "Prime de Noel RSA",
            description: "Versement exceptionnel en decembre pour les beneficiaires du RSA. Attribution automatique.",
            categorie: Categorie::RevenusEmploi,
            montant_min: Some(152.45),
            montant_max: Some(450.0),
            periodicite: "annuel",
            organisme: "CAF / MSA",
            url_info: "https://www.service-public.fr/particuliers/vosdroits/F1325",
            calculer: rules::calc_prime_noel,
        },
    ]
}
