// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(aides_coreFFI)
import aides_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_aides_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_aides_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAidesCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct FfiAideInfo: Equatable, Hashable {
    public var id: String
    public var slug: String
    public var nom: String
    public var description: String
    public var categorie: String
    public var montantMin: Double?
    public var montantMax: Double?
    public var periodicite: String
    public var organisme: String
    public var urlInfo: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, slug: String, nom: String, description: String, categorie: String, montantMin: Double?, montantMax: Double?, periodicite: String, organisme: String, urlInfo: String) {
        self.id = id
        self.slug = slug
        self.nom = nom
        self.description = description
        self.categorie = categorie
        self.montantMin = montantMin
        self.montantMax = montantMax
        self.periodicite = periodicite
        self.organisme = organisme
        self.urlInfo = urlInfo
    }

    

    
}

#if compiler(>=6)
extension FfiAideInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAideInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAideInfo {
        return
            try FfiAideInfo(
                id: FfiConverterString.read(from: &buf), 
                slug: FfiConverterString.read(from: &buf), 
                nom: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                categorie: FfiConverterString.read(from: &buf), 
                montantMin: FfiConverterOptionDouble.read(from: &buf), 
                montantMax: FfiConverterOptionDouble.read(from: &buf), 
                periodicite: FfiConverterString.read(from: &buf), 
                organisme: FfiConverterString.read(from: &buf), 
                urlInfo: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAideInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.slug, into: &buf)
        FfiConverterString.write(value.nom, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.categorie, into: &buf)
        FfiConverterOptionDouble.write(value.montantMin, into: &buf)
        FfiConverterOptionDouble.write(value.montantMax, into: &buf)
        FfiConverterString.write(value.periodicite, into: &buf)
        FfiConverterString.write(value.organisme, into: &buf)
        FfiConverterString.write(value.urlInfo, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAideInfo_lift(_ buf: RustBuffer) throws -> FfiAideInfo {
    return try FfiConverterTypeFfiAideInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAideInfo_lower(_ value: FfiAideInfo) -> RustBuffer {
    return FfiConverterTypeFfiAideInfo.lower(value)
}


public struct FfiAideResult: Equatable, Hashable {
    public var aideId: String
    public var eligible: Bool
    public var montantMensuel: Double?
    public var montantAnnuel: Double?
    public var score: Double
    public var raisons: [String]
    public var raisonsIneligible: [String]
    public var nbEtapes: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(aideId: String, eligible: Bool, montantMensuel: Double?, montantAnnuel: Double?, score: Double, raisons: [String], raisonsIneligible: [String], nbEtapes: UInt8) {
        self.aideId = aideId
        self.eligible = eligible
        self.montantMensuel = montantMensuel
        self.montantAnnuel = montantAnnuel
        self.score = score
        self.raisons = raisons
        self.raisonsIneligible = raisonsIneligible
        self.nbEtapes = nbEtapes
    }

    

    
}

#if compiler(>=6)
extension FfiAideResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAideResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAideResult {
        return
            try FfiAideResult(
                aideId: FfiConverterString.read(from: &buf), 
                eligible: FfiConverterBool.read(from: &buf), 
                montantMensuel: FfiConverterOptionDouble.read(from: &buf), 
                montantAnnuel: FfiConverterOptionDouble.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf), 
                raisons: FfiConverterSequenceString.read(from: &buf), 
                raisonsIneligible: FfiConverterSequenceString.read(from: &buf), 
                nbEtapes: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAideResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.aideId, into: &buf)
        FfiConverterBool.write(value.eligible, into: &buf)
        FfiConverterOptionDouble.write(value.montantMensuel, into: &buf)
        FfiConverterOptionDouble.write(value.montantAnnuel, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
        FfiConverterSequenceString.write(value.raisons, into: &buf)
        FfiConverterSequenceString.write(value.raisonsIneligible, into: &buf)
        FfiConverterUInt8.write(value.nbEtapes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAideResult_lift(_ buf: RustBuffer) throws -> FfiAideResult {
    return try FfiConverterTypeFfiAideResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAideResult_lower(_ value: FfiAideResult) -> RustBuffer {
    return FfiConverterTypeFfiAideResult.lower(value)
}


public struct FfiSimulationResult: Equatable, Hashable {
    public var aidesEligibles: [FfiAideResult]
    public var aidesIneligibles: [FfiAideResult]
    public var totalMensuel: Double
    public var totalAnnuel: Double
    public var calculeLe: String
    public var versionBaremes: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(aidesEligibles: [FfiAideResult], aidesIneligibles: [FfiAideResult], totalMensuel: Double, totalAnnuel: Double, calculeLe: String, versionBaremes: String) {
        self.aidesEligibles = aidesEligibles
        self.aidesIneligibles = aidesIneligibles
        self.totalMensuel = totalMensuel
        self.totalAnnuel = totalAnnuel
        self.calculeLe = calculeLe
        self.versionBaremes = versionBaremes
    }

    

    
}

#if compiler(>=6)
extension FfiSimulationResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSimulationResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSimulationResult {
        return
            try FfiSimulationResult(
                aidesEligibles: FfiConverterSequenceTypeFfiAideResult.read(from: &buf), 
                aidesIneligibles: FfiConverterSequenceTypeFfiAideResult.read(from: &buf), 
                totalMensuel: FfiConverterDouble.read(from: &buf), 
                totalAnnuel: FfiConverterDouble.read(from: &buf), 
                calculeLe: FfiConverterString.read(from: &buf), 
                versionBaremes: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSimulationResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiAideResult.write(value.aidesEligibles, into: &buf)
        FfiConverterSequenceTypeFfiAideResult.write(value.aidesIneligibles, into: &buf)
        FfiConverterDouble.write(value.totalMensuel, into: &buf)
        FfiConverterDouble.write(value.totalAnnuel, into: &buf)
        FfiConverterString.write(value.calculeLe, into: &buf)
        FfiConverterString.write(value.versionBaremes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSimulationResult_lift(_ buf: RustBuffer) throws -> FfiSimulationResult {
    return try FfiConverterTypeFfiSimulationResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSimulationResult_lower(_ value: FfiSimulationResult) -> RustBuffer {
    return FfiConverterTypeFfiSimulationResult.lower(value)
}


public struct FfiSituation: Equatable, Hashable {
    public var age: UInt8
    public var situationFamiliale: String
    public var nbEnfants: UInt8
    public var agesEnfants: Data
    public var logement: String
    public var loyerMensuel: Double
    public var codePostal: String?
    public var zoneApl: UInt8?
    public var revenusNetsMensuels: Double
    public var revenusConjoint: Double
    public var patrimoineEstime: Double
    public var ald: Bool
    public var rqth: Bool
    public var invalidite: Bool
    public var dependance: Bool
    public var gir: UInt8?
    public var cmuC: Bool
    public var emploi: String
    public var ancienneteEmploiMois: UInt32
    public var heuresSemaine: Double
    public var primoAccedant: Bool
    public var etudiantBoursier: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(age: UInt8, situationFamiliale: String, nbEnfants: UInt8, agesEnfants: Data, logement: String, loyerMensuel: Double, codePostal: String?, zoneApl: UInt8?, revenusNetsMensuels: Double, revenusConjoint: Double, patrimoineEstime: Double, ald: Bool, rqth: Bool, invalidite: Bool, dependance: Bool, gir: UInt8?, cmuC: Bool, emploi: String, ancienneteEmploiMois: UInt32, heuresSemaine: Double, primoAccedant: Bool, etudiantBoursier: Bool) {
        self.age = age
        self.situationFamiliale = situationFamiliale
        self.nbEnfants = nbEnfants
        self.agesEnfants = agesEnfants
        self.logement = logement
        self.loyerMensuel = loyerMensuel
        self.codePostal = codePostal
        self.zoneApl = zoneApl
        self.revenusNetsMensuels = revenusNetsMensuels
        self.revenusConjoint = revenusConjoint
        self.patrimoineEstime = patrimoineEstime
        self.ald = ald
        self.rqth = rqth
        self.invalidite = invalidite
        self.dependance = dependance
        self.gir = gir
        self.cmuC = cmuC
        self.emploi = emploi
        self.ancienneteEmploiMois = ancienneteEmploiMois
        self.heuresSemaine = heuresSemaine
        self.primoAccedant = primoAccedant
        self.etudiantBoursier = etudiantBoursier
    }

    

    
}

#if compiler(>=6)
extension FfiSituation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSituation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSituation {
        return
            try FfiSituation(
                age: FfiConverterUInt8.read(from: &buf), 
                situationFamiliale: FfiConverterString.read(from: &buf), 
                nbEnfants: FfiConverterUInt8.read(from: &buf), 
                agesEnfants: FfiConverterData.read(from: &buf), 
                logement: FfiConverterString.read(from: &buf), 
                loyerMensuel: FfiConverterDouble.read(from: &buf), 
                codePostal: FfiConverterOptionString.read(from: &buf), 
                zoneApl: FfiConverterOptionUInt8.read(from: &buf), 
                revenusNetsMensuels: FfiConverterDouble.read(from: &buf), 
                revenusConjoint: FfiConverterDouble.read(from: &buf), 
                patrimoineEstime: FfiConverterDouble.read(from: &buf), 
                ald: FfiConverterBool.read(from: &buf), 
                rqth: FfiConverterBool.read(from: &buf), 
                invalidite: FfiConverterBool.read(from: &buf), 
                dependance: FfiConverterBool.read(from: &buf), 
                gir: FfiConverterOptionUInt8.read(from: &buf), 
                cmuC: FfiConverterBool.read(from: &buf), 
                emploi: FfiConverterString.read(from: &buf), 
                ancienneteEmploiMois: FfiConverterUInt32.read(from: &buf), 
                heuresSemaine: FfiConverterDouble.read(from: &buf), 
                primoAccedant: FfiConverterBool.read(from: &buf), 
                etudiantBoursier: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSituation, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.age, into: &buf)
        FfiConverterString.write(value.situationFamiliale, into: &buf)
        FfiConverterUInt8.write(value.nbEnfants, into: &buf)
        FfiConverterData.write(value.agesEnfants, into: &buf)
        FfiConverterString.write(value.logement, into: &buf)
        FfiConverterDouble.write(value.loyerMensuel, into: &buf)
        FfiConverterOptionString.write(value.codePostal, into: &buf)
        FfiConverterOptionUInt8.write(value.zoneApl, into: &buf)
        FfiConverterDouble.write(value.revenusNetsMensuels, into: &buf)
        FfiConverterDouble.write(value.revenusConjoint, into: &buf)
        FfiConverterDouble.write(value.patrimoineEstime, into: &buf)
        FfiConverterBool.write(value.ald, into: &buf)
        FfiConverterBool.write(value.rqth, into: &buf)
        FfiConverterBool.write(value.invalidite, into: &buf)
        FfiConverterBool.write(value.dependance, into: &buf)
        FfiConverterOptionUInt8.write(value.gir, into: &buf)
        FfiConverterBool.write(value.cmuC, into: &buf)
        FfiConverterString.write(value.emploi, into: &buf)
        FfiConverterUInt32.write(value.ancienneteEmploiMois, into: &buf)
        FfiConverterDouble.write(value.heuresSemaine, into: &buf)
        FfiConverterBool.write(value.primoAccedant, into: &buf)
        FfiConverterBool.write(value.etudiantBoursier, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSituation_lift(_ buf: RustBuffer) throws -> FfiSituation {
    return try FfiConverterTypeFfiSituation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSituation_lower(_ value: FfiSituation) -> RustBuffer {
    return FfiConverterTypeFfiSituation.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiAideInfo: FfiConverterRustBuffer {
    typealias SwiftType = [FfiAideInfo]

    public static func write(_ value: [FfiAideInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiAideInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiAideInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiAideInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiAideInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiAideResult: FfiConverterRustBuffer {
    typealias SwiftType = [FfiAideResult]

    public static func write(_ value: [FfiAideResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiAideResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiAideResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiAideResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiAideResult.read(from: &buf))
        }
        return seq
    }
}
public func listAides() -> [FfiAideInfo]  {
    return try!  FfiConverterSequenceTypeFfiAideInfo.lift(try! rustCall() {
    uniffi_aides_core_fn_func_list_aides($0
    )
})
}
public func simulate(situation: FfiSituation) -> FfiSimulationResult  {
    return try!  FfiConverterTypeFfiSimulationResult_lift(try! rustCall() {
    uniffi_aides_core_fn_func_simulate(
        FfiConverterTypeFfiSituation_lower(situation),$0
    )
})
}
public func supportedLangs() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_aides_core_fn_func_supported_langs($0
    )
})
}
public func translate(lang: String, key: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_aides_core_fn_func_translate(
        FfiConverterString.lower(lang),
        FfiConverterString.lower(key),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_aides_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_aides_core_checksum_func_list_aides() != 59367) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aides_core_checksum_func_simulate() != 31655) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aides_core_checksum_func_supported_langs() != 50100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aides_core_checksum_func_translate() != 45336) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAidesCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all