-- UX Laws data for tracability.db

INSERT INTO ux_laws (udid, code, name, description, source_url, category) VALUES
('UXL001', 'UXL001', 'Aesthetic-Usability Effect', 'Beautiful design perceived as more usable', 'https://lawsofux.com/aesthetic-usability-effect/', 'heuristics'),
('UXL002', 'UXL002', 'Jakobs Law', 'Users expect your site to work like others they know', 'https://lawsofux.com/jakobs-law/', 'heuristics'),
('UXL003', 'UXL003', 'Occams Razor', 'Simplest solution with fewest assumptions is best', 'https://lawsofux.com/occams-razor/', 'heuristics'),
('UXL004', 'UXL004', 'Postels Law', 'Be liberal in what you accept, conservative in what you send', 'https://lawsofux.com/postels-law/', 'heuristics'),
('UXL005', 'UXL005', 'Teslers Law', 'Every system has irreducible complexity', 'https://lawsofux.com/teslers-law/', 'heuristics'),
('UXL006', 'UXL006', 'Cognitive Load', 'Mental resources needed to understand interface', 'https://lawsofux.com/cognitive-load/', 'cognitive'),
('UXL007', 'UXL007', 'Millers Law', 'Working memory holds 7 items', 'https://lawsofux.com/millers-law/', 'cognitive'),
('UXL008', 'UXL008', 'Chunking', 'Group related info into meaningful wholes', 'https://lawsofux.com/chunking/', 'cognitive'),
('UXL009', 'UXL009', 'Working Memory', 'Temporary cognitive storage with limited capacity', 'https://lawsofux.com/working-memory/', 'cognitive'),
('UXL010', 'UXL010', 'Hicks Law', 'Decision time increases with number of choices', 'https://lawsofux.com/hicks-law/', 'cognitive'),
('UXL011', 'UXL011', 'Choice Overload', 'Too many options causes paralysis', 'https://lawsofux.com/choice-overload/', 'cognitive'),
('UXL012', 'UXL012', 'Cognitive Bias', 'Systematic thinking errors affecting judgment', 'https://lawsofux.com/cognitive-bias/', 'cognitive'),
('UXL013', 'UXL013', 'Selective Attention', 'Focus on goal-relevant stimuli only', 'https://lawsofux.com/selective-attention/', 'cognitive'),
('UXL014', 'UXL014', 'Von Restorff Effect', 'Different item among similar ones is remembered', 'https://lawsofux.com/von-restorff-effect/', 'cognitive'),
('UXL015', 'UXL015', 'Serial Position Effect', 'First and last items remembered best', 'https://lawsofux.com/serial-position-effect/', 'cognitive'),
('UXL016', 'UXL016', 'Peak-End Rule', 'Experience judged by peak moment and ending', 'https://lawsofux.com/peak-end-rule/', 'cognitive'),
('UXL017', 'UXL017', 'Zeigarnik Effect', 'Incomplete tasks remembered better', 'https://lawsofux.com/zeigarnik-effect/', 'cognitive'),
('UXL018', 'UXL018', 'Law of Proximity', 'Near objects grouped together', 'https://lawsofux.com/law-of-proximity/', 'visual'),
('UXL019', 'UXL019', 'Law of Similarity', 'Similar elements perceived as group', 'https://lawsofux.com/law-of-similarity/', 'visual'),
('UXL020', 'UXL020', 'Law of Common Region', 'Shared boundary equals group', 'https://lawsofux.com/law-of-common-region/', 'visual'),
('UXL021', 'UXL021', 'Law of Uniform Connectedness', 'Visually connected equals related', 'https://lawsofux.com/law-of-uniform-connectedness/', 'visual'),
('UXL022', 'UXL022', 'Law of Pragnanz', 'Brain prefers simplest interpretation', 'https://lawsofux.com/law-of-pragnanz/', 'visual'),
('UXL023', 'UXL023', 'Fittss Law', 'Time to reach target depends on distance and size', 'https://lawsofux.com/fittss-law/', 'interaction'),
('UXL024', 'UXL024', 'Doherty Threshold', 'Response should be under 400ms', 'https://lawsofux.com/doherty-threshold/', 'interaction'),
('UXL025', 'UXL025', 'Flow State', 'Full immersion in activity', 'https://lawsofux.com/flow/', 'interaction'),
('UXL026', 'UXL026', 'Goal-Gradient Effect', 'Motivation increases near goal', 'https://lawsofux.com/goal-gradient-effect/', 'interaction'),
('UXL027', 'UXL027', 'Paradox of Active User', 'Users never read manuals dive in immediately', 'https://lawsofux.com/paradox-of-the-active-user/', 'interaction'),
('UXL028', 'UXL028', 'Pareto Principle', '80 percent effects from 20 percent causes', 'https://lawsofux.com/pareto-principle/', 'heuristics'),
('UXL029', 'UXL029', 'Parkinsons Law', 'Work expands to fill available time', 'https://lawsofux.com/parkinsons-law/', 'heuristics'),
('UXL030', 'UXL030', 'Mental Model', 'User internal representation of system', 'https://lawsofux.com/mental-model/', 'cognitive');
